### ISSUE TITLE
shelve.open error

### ISSUE THREAD

**Issue by p2ya** [synergylabs/Zodiac#1]
Great work, trying to understand how it works however have some issues at the beginning for opening the shelve file as I get the following error at line
sensors_dict = shelve.open('/Zodiac-master/metadata/bacnetdevices.shelve','r')

error:
anydbm.error: db type could not be determined

Any idea why this happens and how to fix it ?

**Comment by p2ya** [comment]
Also the link as menitoned:
"The Zodiac project home page where we share our raw building metadata, manually labelled ground truth data point types and this source code page can be found here."
doesnt work anymore, any chance to get access to sample data ?

**Comment by bbalaji-ucsd** [comment]
Did you try: bacnet_devices.shelve ? The underscore is missing above.

Also, which version of Python are you using. I think my code is using Python 2.7

Which link is not working? Not sure where the above statement is from

**Comment by bbalaji-ucsd** [comment]
Actually, there was an error in the file. I just fixed it. Thanks for pointing it out.
